### ISSUE TITLE
traci.start() label error

### ISSUE THREAD

**Issue by luckywlj** [Pi-Star-Lab/RESCO#14]
First of all, thank you so much for your project codes. 
When I run the code with IDQN and ingolstadt1, there is such error

<img width="367" alt="error" src="https://user-images.githubusercontent.com/53700751/200846017-624fe2a6-c163-41b2-a080-cb1ef708e118.png">

I know it is the parameter of sumo traci.start(), and I do not modify any code. I check the code and do not find any problems. So can you tell me how to solve it?
My configuration matches the requirements in setup.py, but my sumo version is 1.12.0. Is it related to the sumo version?

**Comment by jault** [comment]
Are you trying to use libsumo, did you set LIBSUMO_AS_TRACI? If that is the case then have you given the argument --libsumo as True as well?

**Comment by luckywlj** [comment]
> Are you trying to use libsumo, did you set LIBSUMO_AS_TRACI? If that is the case then have you given the argument --libsumo as True as well?

Thank you for your answer. Now it is OK.
