### ISSUE TITLE
fma2c_config['supervisors']  not implemented ! 

### ISSUE THREAD

**Issue by mostafanorouzi** [Pi-Star-Lab/RESCO#18]
Hi 
you use fma2c_config['supervisors']  in states definitions but it's not in mdp_config

**Comment by jault** [comment]
It is created based on managers in the mdp_config. See:
https://github.com/Pi-Star-Lab/RESCO/blob/50b628468cba613440c70b9843b6ac45f54d33d9/resco_benchmark/main.py#L68
