### ISSUE TITLE
Cumulative rewards and Delay time after training

### ISSUE THREAD

**Issue by HappyDay-design** [Pi-Star-Lab/RESCO#2]
Thank you for sharing your code. Your code is very helpful but there are some things I don't understand.

After training model _"python main.py --agent IDQN --map ingolstadt21"_ , I found that it generates several files in the logs directory including agent.pt, metric.csv and tripinfor.xml.
But I don't see the cumulative rewards per episode because I want to know when the model converges. And I also don't see where the model is saved, how can I test the model after training (trained_model.h5).
Thank you very much

**Comment by jault** [comment]
The performance output needs some work right now for easier analysis. metrics_x.csv will contain the reward for each agent for each time step for episode x. Summing these would give cumulative reward. Each agent type will need a load function to support separate testing parameters. They'll be included in the next update.
