### ISSUE TITLE
key error when running python main.py --agent IDQN --map ingolstadt21

### ISSUE THREAD

**Issue by FanFan2021** [Pi-Star-Lab/RESCO#23]
always get key error like:

File "/resco_benchmark/agents/agent.py", line 35, in observe
    if info['eps'] % self.config['save_freq'] == 0:
KeyError: 'save_freq'

  File "/resco_benchmark/agents/pfrl_dqn.py", line 43, in observe
    if self.config['load']:
KeyError: 'load'

How to fix this kind of problem?

**Comment by jault** [comment]
Sorry, this should be fixed now. A commit was missing when the library was updated.

https://github.com/Pi-Star-Lab/RESCO/commit/567cece6d0694c1c16b2687df445e02860fb0e9e
