### ISSUE TITLE
Delay calculation

### ISSUE THREAD

**Issue by MagMueller** [Pi-Star-Lab/RESCO#24]
I want to benchmark in a paper against your models. 

How do you calculate the delays, which you plot in your Readme? Is this just the sum of all wait times of each lane for the whole simulation and the divided through the number of cars in the end? Where can I find that?

**Comment by jault** [comment]
Yes, it's the sum of delay (timeLoss) divided by the total number of cars including cars which were unable to spawn (departDelay).

See here for more descriptions of SUMOs output: https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html

The logging function included in /utils/ right now is a bit rough, you need to run readXML.py first, which outputs to the avg_*.py files. I'm currently working on a large update to RESCO so I have created a new graphing/logging function. I still need to test those changes those. Try the graph.py included here (you'll need to set the log_dir variable).

[graph.zip](https://github.com/Pi-Star-Lab/RESCO/files/15196347/graph.zip)
