### ISSUE TITLE
code for processing new traffic network files in signal_config

### ISSUE THREAD

**Issue by sallyqiansun** [Pi-Star-Lab/RESCO#5]
Hi :)
Thank you for sharing the code, I'm wondering if it's possible to get the part of code that you use to generate the signal_config file, since I have a new network and I'd like to test it using the benchmark. Looking forward to your reply! Thanks!

**Comment by jault** [comment]
Hi, unfortunately most of the config was built by hand. It should be possible to do automatically by following the road networks in the network files. However, as there are typically cycles in the networks it can be difficult to determine which signal upstream connects to which signal's downstream. 

For the simple grids used for validation (grid4x4, arterial4x4) this code was used:
https://github.com/Pi-Star-Lab/RESCO/blob/07a7dad3720464437e7a11bd89e25782457c848c/traffic_signal.py#L106

Phase pairs are used from the FRAP/MPLight algorithms. The phase pairs in signal_config correspond to the traffic movements like this:
0: 'S-W',
1: 'S-S',
2: 'S-E',
3: 'W-N',
4: 'W-W',
5: 'W-S',
6: 'N-E',
7: 'N-N',
8: 'N-W',
9: 'E-S',
10: 'E-E',
11: 'E-N'
So the phase pair in ingolstadt1; [1, 7] is S-S (southbound to southbound traffic) and N-N (northbound to northbound traffic). [7, 8]
would allow northbound through traffic as well as left-turning northbound to westbound traffic.
The order of the phase_pairs is determined by the order in the intersection's tlLogic definition here.
Ignoring the lines without priority (capital 'G' gives priority while 'g' does not) green lights:
The first gives priority to lanes serving through traffic northbound and southbound.
<phase duration="38" state="GGgGrGGG"/>
The second gives priority to N-N and N-W.
<phase duration="6" state="GGGrrrrr"/>
The third priority to E-S and E-N,
<phase duration="37" state="rrrGGGrr"/>
So the order of the phase_pairs is: (S-S, N-N), (N-N, N-W), (E-S, E-N), encoded as [1, 7], [7, 8], [9, 11].


The valid acts are indices for parameter sharing algorithms, indicating which actions (defined by the phse pair config) are available to each agent. The order of the valid acts is used to correct differences in order between intersections. One intersection may have a northbound protected left turn as action 1, when another could have it as action 3.  In ingolstadt7 this is the case with the 2nd action for signal 'gneJ207'. So, the action is mapped from phase_pair 3 to gneJ207's action index 1.


Lane sets defines which lanes constitute a cardinal direction on the intersection. Downstream defines which intersections are immediately adjacent.
