### ISSUE TITLE
signal_config

### ISSUE THREAD

**Issue by gioannides** [Pi-Star-Lab/RESCO#8]
Hi, I am trying to use a custom network but I do not understand what the signal_config is doing. I read the previously open issues about it as well. It seems it is a common issue in this repository. Could you provide an explanation? Thanks!

**Comment by jault** [comment]
Hi, I've recently added a more detailed description of the config surrounding environments [here ](https://github.com/Pi-Star-Lab/RESCO/blob/main/resco_benchmark/config/Environment%20Configuration.md). Let me know if this helps and any questions you have - it will help to improve the documentation. Thanks!
